version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: css-loader
    versions:
    - ">= 4.a"
    - "< 5"
  # remove after fixing https://github.com/nextcloud/spreed/issues/4818
  - dependency-name: "@babel/preset-env"
    versions:
    - ">= 7.12.11"
